name: Around Alentejo
favicon: null
layout_spectrum: 0.8759047919884324
typography_spectrum: 0.5765023131389171
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4b81c7'
    - '#e5a164'
    - '#c97841'
    - '#73371d'
    - '#bfbbaf'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
