name: Around Alentejo
favicon: null
layout_spectrum: 0.8759047919884324
typography_spectrum: 0.5765023131389171
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4882021648809314
  lightness: 0.8510881494730711
  saturation: 0.8153201616369188
  rhythmicContrast: 0.35338152875192463
purpose: []
